/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as TraysCoolersRouteImport } from './routes/trays-coolers'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBulkOrdersRouteImport } from './routes/admin.bulk-orders'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCateringPackagesRouteImport } from './routes/admin.catering-packages'
import { Route as AdminCateringRequestsRouteImport } from './routes/admin.catering-requests'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as CateringInquiryRouteImport } from './routes/catering.inquiry'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const TraysCoolersRoute = TraysCoolersRouteImport.update({
  id: '/trays-coolers',
  path: '/trays-coolers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkOrdersRoute = AdminBulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCateringPackagesRoute = AdminCateringPackagesRouteImport.update({
  id: '/catering-packages',
  path: '/catering-packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCateringRequestsRoute = AdminCateringRequestsRouteImport.update({
  id: '/catering-requests',
  path: '/catering-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const CateringInquiryRoute = CateringInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => CateringRoute,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catering': typeof CateringRouteWithChildren
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/trays-coolers': typeof TraysCoolersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bulk-orders': typeof AdminBulkOrdersRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/catering-packages': typeof AdminCateringPackagesRoute
  '/admin/catering-requests': typeof AdminCateringRequestsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/catering/inquiry': typeof CateringInquiryRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catering': typeof CateringRouteWithChildren
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/trays-coolers': typeof TraysCoolersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bulk-orders': typeof AdminBulkOrdersRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/catering-packages': typeof AdminCateringPackagesRoute
  '/admin/catering-requests': typeof AdminCateringRequestsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/catering/inquiry': typeof CateringInquiryRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catering': typeof CateringRouteWithChildren
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/trays-coolers': typeof TraysCoolersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bulk-orders': typeof AdminBulkOrdersRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/catering-packages': typeof AdminCateringPackagesRoute
  '/admin/catering-requests': typeof AdminCateringRequestsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/catering/inquiry': typeof CateringInquiryRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catering'
    | '/contact'
    | '/delivery'
    | '/login'
    | '/menu'
    | '/our-story'
    | '/trays-coolers'
    | '/admin/analytics'
    | '/admin/bulk-orders'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/catering-packages'
    | '/admin/catering-requests'
    | '/admin/media'
    | '/admin/settings'
    | '/catering/inquiry'
    | '/menu/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catering'
    | '/contact'
    | '/delivery'
    | '/login'
    | '/menu'
    | '/our-story'
    | '/trays-coolers'
    | '/admin/analytics'
    | '/admin/bulk-orders'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/catering-packages'
    | '/admin/catering-requests'
    | '/admin/media'
    | '/admin/settings'
    | '/catering/inquiry'
    | '/menu/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catering'
    | '/contact'
    | '/delivery'
    | '/login'
    | '/menu'
    | '/our-story'
    | '/trays-coolers'
    | '/admin/analytics'
    | '/admin/bulk-orders'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/catering-packages'
    | '/admin/catering-requests'
    | '/admin/media'
    | '/admin/settings'
    | '/catering/inquiry'
    | '/menu/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CateringRoute: typeof CateringRouteWithChildren
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  TraysCoolersRoute: typeof TraysCoolersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trays-coolers': {
      id: '/trays-coolers'
      path: '/trays-coolers'
      fullPath: '/trays-coolers'
      preLoaderRoute: typeof TraysCoolersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-orders': {
      id: '/admin/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/admin/bulk-orders'
      preLoaderRoute: typeof AdminBulkOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catering-packages': {
      id: '/admin/catering-packages'
      path: '/catering-packages'
      fullPath: '/admin/catering-packages'
      preLoaderRoute: typeof AdminCateringPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catering-requests': {
      id: '/admin/catering-requests'
      path: '/catering-requests'
      fullPath: '/admin/catering-requests'
      preLoaderRoute: typeof AdminCateringRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/catering/inquiry': {
      id: '/catering/inquiry'
      path: '/inquiry'
      fullPath: '/catering/inquiry'
      preLoaderRoute: typeof CateringInquiryRouteImport
      parentRoute: typeof CateringRoute
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof MenuRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBulkOrdersRoute: typeof AdminBulkOrdersRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCateringPackagesRoute: typeof AdminCateringPackagesRoute
  AdminCateringRequestsRoute: typeof AdminCateringRequestsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBulkOrdersRoute: AdminBulkOrdersRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCateringPackagesRoute: AdminCateringPackagesRoute,
  AdminCateringRequestsRoute: AdminCateringRequestsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CateringRouteChildren {
  CateringInquiryRoute: typeof CateringInquiryRoute
}

const CateringRouteChildren: CateringRouteChildren = {
  CateringInquiryRoute: CateringInquiryRoute,
}

const CateringRouteWithChildren = CateringRoute._addFileChildren(
  CateringRouteChildren,
)

interface MenuRouteChildren {
  MenuSlugRoute: typeof MenuSlugRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuSlugRoute: MenuSlugRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CateringRoute: CateringRouteWithChildren,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  TraysCoolersRoute: TraysCoolersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
